node_env: "development"
url_db: "postgres://postgres:123456@localhost:5432/farm_service_db?sslmode=disable"
name_service: "FarmService"
port_grpc: 50054
host_grpc: "localhost"
interval_check: "20s"
timeout_check: "15s"
